name: Deploy to AWS

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy-production:
    name: Deploy(Production)
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: echo 'yarn cache hit!'
      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: echo 'yarn cache missed!'
      - run: yarn install --immutable --immutable-cache --check-cache

#       - name: Generate Environment Variables File for Production
#         run: |
#           echo "REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL" >> .env.production
#         env:
#           REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

      - name: Build
        run: unset CI && yarn build

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'build'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: '/index.html'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
